spring:
  application:
    name: pos-discovery

server:
  port: 8888
  wait-time-in-ms-when-sync-empty: 0
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka