eureka:
    client:
        service-url:
            defaultZone: http://localhost:8888/eureka/
server:
    port: 8080
spring:
    application:
        name: pos-gateway
    cloud:
        gateway:
            routes: '[{id=pos-products-service, uri=lb://pos-products, predicates=[Path=/api/products/**,
                Method=GET], filters=[{name=Hystrix, args={name=fallbackCommand, fallbackUri=forward:/fallback/message}}]},
                {id=pos-carts-service, uri=lb://pos-carts, predicates=[Path=/api/cart/**,
                Method=[GET, POST, PUT, DELETE]], filters=[{name=Hystrix, args={name=fallbackCommand,
                fallbackUri=forward:/fallback/message}}]}]'
