#server:
#  port: 8080
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8083/eureka
#
#spring:
#  application:
#    name: pos-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: products-service
#          uri: lb://products-service
#          predicates:
#            - Path=/api/products/**
#        - id: carts-service
#          uri: lb://carts-service
#          predicates:
#            - Path=/api/carts/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: pos-products-service
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**
            - Method=GET
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: pos-carts-service
          uri: lb://pos-carts
          predicates:
            - Path=/api/cart/**
            - Method=[GET, POST, PUT, DELETE]
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message

